### PR TITLE
Correct answer reveal mechanic

### PR DESCRIPTION
**Pull request by chanmSC**
Added a little mechanic to cycle through the mask fraction images (1, 3, 5, 7, 9, 10) to reveal the full image of a correctly answered animal.

Also added a button underneath the reveal image to click to go to "Next Animal" question, so they can stare at the pretty images and show their fam and friends for as long as they'd like before going to the next image puzzle.

I also added a longer delay before auto submission at the end of guess all answers correct, so ppl can also enjoy the lobster image reveal at the end.

(Hope you don't mind that I added this to your puzzle Gary! Sorry to take away your v2 feature!

Stephen also wanted it, and you said you wanted it, and I also thought it'd be nice to reward the ppl who answer the questions correctly on the first try to have the opportunity to see the full images too 😅)

### CODE REVIEW

**Comment by stmudie** [comment]
Pretty cool! I haven't looked at the code yet, but I have tested. The only issue I see is some weirdness on the reveal of the last animal. Two images overlaying either other or something...
Screenshot from 2024-10-11 21-52-26

**Comment by chanmSC** [comment]
Lollll, fixed it, good catch, I forgot to check that last image on wider breakpoints.

**Comment by gazzar** [comment]
I just saw your email Michelle. This sounds awesome. Thank you! In light of Stephen's checking and your subsequent fixing, I am happy for Stephen to approve it, but if I get to it first, I'll take a look and test a bit tomorrow and approve it.

**Review by stmudie — APPROVED** [review]
Lovely!

**Comment by stmudie** [comment]
> I just saw your email Michelle. This sounds awesome. Thank you! In light of Stephen's checking and your subsequent fixing, I am happy for Stephen to approve it, but if I get to it first, I'll take a look and test a bit tomorrow and approve it.

I have approved it Gary - but please give it a thorough test if you have time.

**Comment by gazzar** [comment]
I tested with a few playthroughs. It all worked perfectly! I think that even if  I fiddle with the text to shorten the title to a single line and reduce the preamble to help it fit, it will probably still require vertical scrolling, so I'll leave it as is and not risk breaking anything.

**Pull request merged**
