### PR TITLE
Lf add puzzle shuffleanagram

### PR DESCRIPTION
**Pull request by luigiferiani**
Simple anagram puzzle(s), with the ability to shuffle the letters. 
The puzzles have been chosen so that each of them has 2 anagrams that make sense. 
One of the two words is a common word, and is presented as the initial word (as well as being used as "sub-name" for the puzzle, for ease of debugging), 
The other word is a synchrotron-related word (the answer)
e.g. (but not synch-related): `arc` and `car` are anagrams of each other. `arc` would be used as a "sub-name" for the puzzle, and as an initial word, but the answer would be `car`

### CODE REVIEW

**Comment by luigiferiani** [comment]
(lf-add-puzzle-labelthemap contains this puzzle too, you can review that one if you want to look at all the puzzles at once)

**Comment by stmudie** [comment]
Fantastic work. Can you please rebase from main and resolve conflicts. Then I will approve. The conflicts are in pyproject/uv.lock. I have put pytest-asyncio in dev dependencies, not the normal dependencies.

**Review by stmudie — DISMISSED** [review]
Lovely work. Beautiful puzzle!

**Review by stmudie — APPROVED** [review]
Lovely work, beautiful puzzle!

**Review by stmudie — APPROVED** [review]

**Review by stmudie — APPROVED** [review]

**Review by stmudie — DISMISSED** [review]

**Review by stmudie — APPROVED** [review]

**Pull request merged**
