### PR TITLE
FIxed Wordsearch Successful Submission Page Heading Bug

### PR DESCRIPTION
**Pull request by chanmSC**
The clash was happening because the style applied on h1 was being using on the submission page somehow.

I moved it into its own css class `.heading-h1` so it doesn't apply directly to `h1`, so this should fix it. But I can't test this locally because the word-search-generator package doesn't work for me, so if you could double check and test that @stmudie that would be great! 🙏

I also bumped the padding on mobile around the letters so there's more space to tap each letter without accidentally tapping the letters next to it.

### CODE REVIEW

**Comment by stmudie** [comment]
This renders the correct page now - but for some reason no confetti?

**Comment by luigiferiani** [comment]
I think the reason is that the submission javascript takes the html returned by the submission page and subs it to the html of the puzzle page. See URL here:
image
usually upon submission that changes to `[etcetc]/submission`
Confetti are set to trigger on DOM loading and it does not work when subbing html in (does something similar when you submit with htmx)

**Comment by chanmSC** [comment]
@luigiferiani @stmudie Ah! Yes, because it's a 'fake' success page! Great catch!

As you said, the JS was POST-ing to `/submission`, getting the response HTML page, then replacing the HTML content of the current page with the response.

Old submission:
image

New submission:
image
image

I've updated the html & JS to submit without JS so it will redirect to the real static pages.

(And updated the JS to automatically store & update the hidden answer string as users add words, so the HTML submit button is good to go whenever the user clicks on it.)

**Review by stmudie — APPROVED** [review]
Looks good.

**Pull request merged**
